### ISSUE TITLE
kibana authentication example?

### ISSUE THREAD

**Issue by privosoft** [floragunncom/search-guard-docs#1]

**Comment by floragunncom** [comment]
Configuring Kibana is in the making. Expect a first draft by tomorrow :)

**Comment by floragunncom** [comment]
We've added the chapter "Using Search Guard with Kibana" to the docs: https://github.com/floragunncom/search-guard-docs/blob/master/kibana.md

Please let us know if something is missing or unclear!

Thanks!

**Comment by privosoft** [comment]
Works!






On Sat, Jun 18, 2016 at 5:52 PM -0400, "floragunn UG" <notifications@github.com<mailto:notifications@github.com>> wrote:


We've added the chapter "Using Search Guard with Kibana" to the docs: https://github.com/floragunncom/search-guard-docs/blob/master/kibana.md

Please let us know if something is missing or unclear!

Thanks!

-
